// Static list of licensed banks operating in Vietnam, used to populate the
// bank dropdown on campaign create/edit forms. Not fetched from an external
// API so the form keeps working even if a third party is unreachable.
export const VN_BANKS: string[] = [
  'Agribank',
  'Vietcombank',
  'VietinBank',
  'BIDV',
  'ACB',
  'Techcombank',
  'MB Bank',
  'VPBank',
  'Sacombank',
  'HDBank',
  'TPBank',
  'SHB',
  'VIB',
  'Eximbank',
  'MSB',
  'OCB',
  'SeABank',
  'SCB',
  'Nam A Bank',
  'ABBANK',
  'PVcomBank',
  'Bac A Bank',
  'BaoViet Bank',
  'VietABank',
  'VietBank',
  'Kienlongbank',
  'LPBank',
  'NCB',
  'PGBank',
  'Saigonbank',
  'DongA Bank',
  'GPBank',
  'CBBank',
  'Oceanbank',
  'Co-opBank',
  'Standard Chartered Việt Nam',
  'HSBC Việt Nam',
  'Shinhan Bank Việt Nam',
  'Woori Bank Việt Nam',
  'UOB Việt Nam',
  'CIMB Việt Nam',
  'Public Bank Việt Nam',
  'Hong Leong Bank Việt Nam',
  'Indovina Bank',
];
